### ISSUE TITLE
Elm 0.19.1: elm-review tests / subproject tests

### ISSUE THREAD

**Issue by lydell** [elm-explorations/test#114]
Hi!

I bumped into an issue after upgrading to Elm 0.19.1. Here’s my story.

I recently started trying out [elm-review](https://package.elm-lang.org/packages/jfmengels/elm-review/latest/). It’s really cool! It lets you write rules that find mistakes in your code.

Running `elm-review init` creates a `review/` folder in your project. The cool thing about elm-review is that its config and rules are written in Elm. So the `review/` folder is its own Elm project, with its own elm.json and dependencies.

It’s possible to install review rules from package.elm-lang.org, but it’s also possible to make company specific rules that help your team not repeat mistakes you’ve made before. That’s what I did.

Custom rules are defined in `review/`. To know that your rules works, you write tests for them. I placed these in `review/tests/`, so that they have access to the rule files and all dependencies (such as [elm-syntax](https://package.elm-lang.org/packages/stil4m/elm-syntax/latest/)).

In Elm 0.19.0, I ran the tests for my actual Elm application using:

```
npx elm-test tests/
```

And the review rule tests using:

```
npx elm-test review/tests/
```

And that worked fine. After upgrading to Elm 0.19.1, `npx elm-test review/tests/` refuses to run. (`npx elm-test tests/` still runs fine.)

Here’s how to reproduce the problem and see the failure:

```
# Create a project for debugging:
❯ gmkdir -p elm-test-issue
❯ cd elm-test-issue

# Install Elm, elm-review and elm-test:
❯ echo '{"private":true}' > package.json
❯ npm i elm elm-review elm-test

# Initialize Elm app:
❯ npx elm init

# Initialize tests for the Elm app:
❯ npx elm-test init

# Initialize elm-review:
❯ npx elm-review init

# Initialize tests for review rules:
❯ cd review
❯ npx elm-test init
❯ cd ..

# Check that running the tests for the Elm app works:
❯ npx elm-test tests

elm-test 0.19.1
---------------

Running 1 test. To reproduce these results, run: elm-test --fuzz 100 --seed 22270649045858 /Users/lydell/stuff/elm-test-issue/tests/Example.elm


TEST RUN INCOMPLETE because there is 1 TODO remaining

Duration: 124 ms
Passed:   0
Failed:   0
Todo:     1
↓ Example
◦ TODO: Implement our first test. See https://package.elm-lang.org/packages/elm-explorations/test/latest for how to do this!

# Trying to run the tests for the review rules fails:
❯ npx elm-test review/tests
npx elm-test review/tests
-- CONFUSING FILE --------------------------------------------------------------

I am getting confused when I try to compile this file:

    /Users/lydell/stuff/elm-test-issue/review/tests/Example.elm

I always check if files appear in any of the "source-directories" listed in your
elm.json to see if there might be some cached information about them. That can
help me compile faster! But in this case, it looks like this file may be in
either of these directories:

    /Users/lydell/stuff/elm-test-issue/review
    /Users/lydell/stuff/elm-test-issue/review/tests

Try to make it so no source directory contains another source directory!

Compilation failed while attempting to build /Users/lydell/stuff/elm-test-issue/review/tests/Example.elm

# Random debug attempt: What if we change from `"source-directories": ["."]` to `"source-directories": ["review"]`?
# Notice the odd "../../../../../review" in the output below.
❯ vim review/elm.json
❯ npx elm-test review/tests
-- MISSING SOURCE DIRECTORY ------------------------------------------- elm.json

I need a valid elm.json file, but the "source-directories" field lists the
following directory:

    ../../../../../review

I cannot find it though. Is it missing? Is there a typo?

Compilation failed while attempting to build /Users/lydell/stuff/elm-test-issue/review/tests/Example.elm

# Random debug attempt: What if you skip `npx` and run the `elm-test` binary directly?
❯ ./node_modules/.bin/elm-test review/tests
Unhandled exception while running the tests: Error: Cannot find elm executable, make sure it is installed.
(If elm is not on your path or is called something different the --compiler flag might help.)
    at Object.<anonymous> (/Users/lydell/stuff/elm-test-issue/node_modules/elm-test/lib/elm-test.js:102:11)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/lydell/stuff/elm-test-issue/node_modules/elm-test/bin/elm-test:3:1)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
    at internal/main/run_main_module.js:17:11
```

Here’s a ready-to-clone repo for your convenience: https://github.com/lydell/elm-test-elm-review-issue

I’m not sure if this is my fault, a problem in elm-test or a problem in elm-review. Or a bit of them all. I hope it’s OK to open the issue here! Let’s see if we can figure out what’s going on and what potential solutions could be!

/cc @jfmengels

**Comment by lydell** [comment]
@rtfeldman Should this issue be moved to rtfeldman/node-test-runner?

**Comment by mblandfo** [comment]
I ran into this same error trying to go through the Exercism Elm track. For example:

Raindrops.elm
tests/Tests.elm

elm-test Fails on 0.19.1, works on 0.19.0

Error is "Try to make it so no source directory contains another source directory!"

I believe "source directory" refers to the "source-directories" setup in elm.json.
So the "Raindrops" project just has ["."], but probably the elm-test node module has "tests" as a source directory, which is a subdirectory of another source directory and causing the issue.

A fix is to update the project like this:

src/Raindrops.elm
tests/Tests.elm

and change elm.json "source-directories" from ["."] to ["src"]

**Comment by jfmengels** [comment]
@lydell I think this should be moved to `rtfeldman/node-test-runner`.

One piece of information that might help here is that `elm-explorations/test` is containd in the dependencies of `jfmengels/elm-review`, and I could imagine that the CLI is "surprised" by this.
