### ISSUE TITLE
Running `elm-test init` without elm installed locally

### ISSUE THREAD

**Issue by lpil** [elm-explorations/test#30]
I always install Elm locally in my projects and run it from `./node_modules/.bin`.  For this to work with `elm-test` I use the `--compiler` flag, though it seems this doesn't work with the `elm-test init` command.

```
$ ./node_modules/.bin/elm-test init --compiler ./node_modules/.bin/elm
/bin/sh: 1: elm: not found
Unable to create temporary directory for elm-test install. { Error: Command failed: elm install elm-explorations/test
    at checkExecSyncError (child_process.js:603:11)
    at Object.execSync (child_process.js:640:13)
    at Object.install (/home/louis/src/waive/assets/node_modules/elm-test/lib/install.js:54:19)
    at Object.<anonymous> (/home/louis/src/waive/assets/node_modules/elm-test/lib/elm-test.js:160:11)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/louis/src/waive/assets/node_modules/elm-test/bin/elm-test:3:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 6077,
  stdout: null,
  stderr: null }
```

What's the recommended method for using `elm-test init` without globally install Elm?

**Comment by lpil** [comment]
Now that I've passed the `elm-test init` step (I temporarily installed `elm` globally) I seem to have the same problem with the other commands

```
$ ./node_modules/.bin/elm-test --compiler ./node_modules/.bin/elm
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/louis/src/waive/assets/node_modules/elm/unpacked_bin/elm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
Compilation failed while attempting to build /home/louis/src/waive/assets/tests/Example.elm
```

**Comment by mgold** [comment]
Sounds like a bug in the node runner, [rtfeldman/node-test-runner](https://github.com/rtfeldman/node-test-runner/issues/new), not the Elm code. Please file over there.

**Comment by lpil** [comment]
My bad, thank you
